### ISSUE TITLE
TODO 📖: Sync todos with Fauna

### ISSUE THREAD

**Issue by marconneves** [MarconWillian-Study/_ignite-todo#2]
Create service and api for edit and sync your todos in all devices.

API:
- [x] List all todos
- [x] Create a new todo
- [x] Delete a todo
- [x] Mark with check a todo
- [x] Mark with uncheck a todo

Application:
- [ ] Instal React Query for internal cache
- [ ] Is is off, add actions to a list for execute after
